version: '3'
services:
  prospector:
    image: nextier/prospector:latest
    ports:
      - "5000:5000"
    volumes:
      - /opt/prospector/scans:/app/scans
      - /opt/prospector/instance:/app/instance
      - /opt/prospector/log:/app/log
      - /opt/prospector/excel_reports:/app/excel_reports
      - /opt/prospector/config.json:/app/config.json
      - /opt/prospector/client_config.json:/app/client_config.json
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0
    restart: always

